### ISSUE TITLE
Green Box Bug

### ISSUE THREAD

**Issue by rfairooz** [designatucr/designverse2024#45]
<img width="809" alt="Screenshot 2023-11-29 at 5 54 06 PM" src="https://github.com/designatucr/designverse2024/assets/91511317/75f919a0-94b7-4efc-a55b-80d526d3369c">

Make sure the objects inside the box do not go out. Try min-w-fit

**Comment by Fuyuki325** [comment]
I changed the text sizes and the 4 orange buttons with breakpoints instead of the actual green box. Let me know if this works. I didn't try min-w-fit yet.
